package org.openscreentime.shared.model

/**
 * Ambient, not-in-a-moment-of-friction version of the same habit-replacement idea behind
 * #12 and #16: a concrete alternative works better than just removing screen time and
 * leaving the urge unresolved. See #17.
 *
 * One tip per calendar day (see [currentDayIndex]), focused on two themes: connecting
 * with other people, and exercising outside - framed differently for each audience. The
 * kid app shows [KID_DAILY_TIPS] (things for the kid to do, solo or with a parent), the
 * parent app shows [PARENT_DAILY_TIPS] (things a parent can do, mostly together with
 * their kid). 365 tips each - a full year before either list repeats.
 */
val KID_DAILY_TIPS = listOf(
    "Today, go for a walk.",
    "Today, go for a jog.",
    "Today, go for a bike ride.",
    "Today, shoot some hoops.",
    "Today, kick a ball around.",
    "Today, jump rope for a while.",
    "Today, practice throwing and catching.",
    "Today, fly a kite.",
    "Today, do some stretches outside.",
    "Today, do a set of jumping jacks.",
    "Today, practice a sport skill you want to improve.",
    "Today, climb around on a playground.",
    "Today, practice cartwheels.",
    "Today, go rollerblading.",
    "Today, ride a scooter around the block.",
    "Today, go skateboarding.",
    "Today, try a balance challenge, like walking a curb.",
    "Today, take a walk around the block.",
    "Today, explore a park you haven't been to.",
    "Today, go for a swim.",
    "Today, hike a trail near you.",
    "Today, play hopscotch.",
    "Today, try a jump rope challenge.",
    "Today, set up a mini obstacle course in the yard.",
    "Today, go birdwatching for a bit.",
    "Today, skip stones at a pond or lake.",
    "Today, build a sandcastle.",
    "Today, try yoga outside.",
    "Today, dance outside to your favorite song.",
    "Today, rake some leaves.",
    "Today, sweep the porch or driveway.",
    "Today, help wash the car outside.",
    "Today, help out in the garden.",
    "Today, water the plants outside.",
    "Today, walk the dog.",
    "Today, shoot some free throws.",
    "Today, practice dribbling a soccer ball.",
    "Today, jump on a trampoline.",
    "Today, practice a handstand or cartwheel.",
    "Today, do a nature scavenger hunt in your yard.",
    "Today, look for shapes in the clouds.",
    "Today, watch the sunset from outside.",
    "Today, collect interesting leaves or rocks on a walk.",
    "Today, try a new outdoor game you've never played.",
    "Today, do a lap or two around the yard.",
    "Today, practice your bike-riding skills.",
    "Today, go for a scooter ride.",
    "Today, try jumping rope backwards.",
    "Today, do a stretching routine outside.",
    "Today, walk somewhere close instead of getting a ride.",
    "Today, practice kicking a ball into a goal.",
    "Today, try skipping instead of walking for a bit.",
    "Today, do wall push-ups outside.",
    "Today, try balancing on one foot for as long as you can.",
    "Today, practice your best cartwheel.",
    "Today, go outside and count how many different birds you see.",
    "Today, try racing yourself around the yard and beat your time.",
    "Today, practice catching a ball with one hand.",
    "Today, go outside and just run around for fun.",
    "Today, practice your jump shot.",
    "Today, try hula hooping outside.",
    "Today, practice riding your bike with no hands, carefully and somewhere safe.",
    "Today, go for a walk and notice five different trees.",
    "Today, try a cartwheel contest with yourself.",
    "Today, practice long jump in the yard.",
    "Today, see how many jumping jacks you can do in a minute.",
    "Today, practice balancing while walking heel-to-toe.",
    "Today, try skipping rocks across water.",
    "Today, go outside and do ten minutes of any sport you like.",
    "Today, practice a new trick on your bike or scooter.",
    "Today, walk to a nearby spot instead of riding.",
    "Today, spend recess time being active outside.",
    "Today, try climbing something safe, like a low tree or rock.",
    "Today, go outside and try to spot animals or insects.",
    "Today, practice your throwing arm.",
    "Today, do a set of squats or lunges outside.",
    "Today, try walking backwards safely in the yard.",
    "Today, practice dribbling a basketball around obstacles.",
    "Today, go for a walk and time yourself.",
    "Today, try a scavenger hunt for different colors outside.",
    "Today, do some outdoor stretching before bed.",
    "Today, practice your serve if you play a racket sport.",
    "Today, go outside and try three new stretches.",
    "Today, walk laps around your yard while listening to music.",
    "Today, try an outdoor workout video.",
    "Today, practice your goalie skills if you play soccer.",
    "Today, go outside and just move for 20 minutes.",
    "Today, play tag with a friend.",
    "Today, play catch with someone.",
    "Today, go for a bike ride with a friend.",
    "Today, shoot hoops with a friend.",
    "Today, play frisbee with someone.",
    "Today, have a jump rope contest.",
    "Today, play hide and seek outside.",
    "Today, have a race around the yard with someone.",
    "Today, play badminton with a friend.",
    "Today, build an obstacle course with a friend.",
    "Today, play soccer with friends.",
    "Today, go for a walk with a family member.",
    "Today, go for a hike with a friend.",
    "Today, play catch with a parent.",
    "Today, have a water balloon toss with someone.",
    "Today, do a scavenger hunt with a friend.",
    "Today, play tag with your siblings.",
    "Today, go for a bike ride with family.",
    "Today, play basketball with a friend.",
    "Today, have a three-legged race with someone.",
    "Today, play hopscotch with a friend.",
    "Today, fly a kite with someone.",
    "Today, go stargazing with your family.",
    "Today, play catch with a sibling.",
    "Today, have a dance party outside with friends.",
    "Today, play a pickup game of soccer.",
    "Today, race a friend to the end of the block.",
    "Today, play catch with a neighbor.",
    "Today, go for a walk with the family dog.",
    "Today, build a fort outside with a friend.",
    "Today, have a jumping contest to see who can jump farthest.",
    "Today, play a game of tag at the park.",
    "Today, go biking with a sibling.",
    "Today, teach a friend a sport move you know.",
    "Today, have a hula hoop contest.",
    "Today, play a backyard game with the whole family.",
    "Today, kick a ball around with a parent.",
    "Today, go for a walk and talk with a grandparent.",
    "Today, have a relay race in the yard.",
    "Today, play catch until you drop the ball five times.",
    "Today, go exploring outside with a friend.",
    "Today, play a game of horse at the basketball hoop.",
    "Today, have a handstand contest with a friend.",
    "Today, go for a walk with a neighbor's kid.",
    "Today, play tug of war with friends.",
    "Today, have a bike race around the block.",
    "Today, play a game of capture the flag.",
    "Today, go on a bug hunt with a sibling.",
    "Today, have a cartwheel contest with friends.",
    "Today, play catch with a football.",
    "Today, build a sandcastle with a friend.",
    "Today, go for a walk and collect things with a sibling.",
    "Today, play wiffle ball with friends.",
    "Today, have a jump-rope double-dutch session.",
    "Today, play a game of kickball.",
    "Today, go for a swim with family or friends.",
    "Today, play a game of four square.",
    "Today, call a grandparent and ask about their week.",
    "Today, video chat a relative who lives far away.",
    "Today, write a letter to a friend or family member.",
    "Today, write a thank-you note to someone.",
    "Today, give a genuine compliment to someone in your family.",
    "Today, ask a parent or sibling about their day.",
    "Today, teach a family member something you know.",
    "Today, ask someone to teach you a skill.",
    "Today, play a board game with someone at home.",
    "Today, help a neighbor with a small task.",
    "Today, do something kind for a sibling.",
    "Today, have a phone-free conversation with a parent.",
    "Today, invite a friend over to hang out.",
    "Today, thank someone who has helped you recently.",
    "Today, reconnect with a friend you haven't talked to in a while.",
    "Today, tell a family member something you appreciate about them.",
    "Today, ask a grandparent what they were like as a kid.",
    "Today, do a favor for someone without being asked.",
    "Today, listen to a family member tell a story.",
    "Today, help plan a family activity.",
    "Today, cook or bake something with a family member.",
    "Today, share something you made with someone.",
    "Today, ask someone for help learning something new.",
    "Today, introduce yourself to a new neighbor.",
    "Today, help out with a volunteer or community activity.",
    "Today, say something kind to a family member.",
    "Today, check in on a friend to see how they're doing.",
    "Today, send a postcard or note to someone far away.",
    "Today, give someone a hug and tell them you appreciate them.",
    "Today, make a card for someone.",
    "Today, ask a friend to join you for an activity.",
    "Today, have breakfast with family and really talk.",
    "Today, tell a family member a joke to make them laugh.",
    "Today, share a favorite memory with someone.",
    "Today, ask someone to teach you their favorite recipe.",
    "Today, offer to help a neighbor with yard work.",
    "Today, write a note of encouragement for someone.",
    "Today, ask a friend about their favorite hobby.",
    "Today, plan a game night with your family.",
    "Today, help a younger sibling or cousin with something.",
    "Today, ask a parent to tell you a story from when they were young.",
    "Today, sit down with family and talk about your day, no screens.",
    "Today, tell a friend something you're thankful for about them.",
    "Today, ask a grandparent or older relative for advice about something.",
    "Today, help set the table and eat dinner together as a family.",
    "Today, make plans with a friend to do something in person.",
    "Today, ask a sibling to play a game with you.",
    "Today, share a story from your day with someone at dinner.",
    "Today, give a compliment to someone outside your family.",
    "Today, help a family member with a chore they're doing.",
    "Today, ask someone in your family what made them smile.",
    "Today, tell a friend what you like about them.",
    "Today, call a friend instead of texting them.",
    "Today, ask a neighbor how their day is going.",
    "Today, spend time really listening when someone talks to you.",
    "Today, thank a teacher, coach, or mentor for something they've done.",
    "Today, ask a family member to teach you something from their childhood.",
    "Today, plan a surprise nice gesture for someone in your family.",
    "Today, ask a grandparent about their favorite memory.",
    "Today, help a friend who's having a hard day.",
    "Today, share your favorite book or show with someone and talk about it.",
    "Today, ask a family member what they're looking forward to.",
    "Today, sit with a grandparent and look through old photos together.",
    "Today, ask a parent what their job is actually like.",
    "Today, make breakfast for your family.",
    "Today, write down something nice about each person in your family.",
    "Today, invite someone new to sit with you at lunch.",
    "Today, ask a cousin or relative about their favorite hobby.",
    "Today, help a sibling practice something they're working on.",
    "Today, share your day's highlight with your family at dinner.",
    "Today, teach a younger kid a game you used to love.",
    "Today, ask your parents how they met, or a favorite family story.",
    "Today, write a list of questions and ask a grandparent.",
    "Today, thank a friend for something specific they did.",
    "Today, offer to help clean up without being asked, alongside family.",
    "Today, ask a family member for a recommendation - book, show, or game.",
    "Today, plan a fun surprise for a sibling.",
    "Today, practice really listening without interrupting, all day.",
    "Today, ask a friend what they're proud of lately.",
    "Today, tell your family about something you learned.",
    "Today, make a small gift for someone you care about.",
    "Today, ask a grandparent to teach you a skill they have.",
    "Today, invite a friend to try a new activity with you.",
    "Go for a walk.",
    "Go for a jog.",
    "Go for a bike ride.",
    "Shoot some hoops.",
    "Kick a ball around.",
    "Jump rope for a while.",
    "Practice throwing and catching.",
    "Fly a kite.",
    "Do some stretches outside.",
    "Do a set of jumping jacks.",
    "Practice a sport skill you want to improve.",
    "Climb around on a playground.",
    "Practice cartwheels.",
    "Go rollerblading.",
    "Ride a scooter around the block.",
    "Go skateboarding.",
    "Try a balance challenge, like walking a curb.",
    "Take a walk around the block.",
    "Explore a park you haven't been to.",
    "Go for a swim.",
    "Hike a trail near you.",
    "Play hopscotch.",
    "Try a jump rope challenge.",
    "Set up a mini obstacle course in the yard.",
    "Go birdwatching for a bit.",
    "Skip stones at a pond or lake.",
    "Build a sandcastle.",
    "Try yoga outside.",
    "Dance outside to your favorite song.",
    "Rake some leaves.",
    "Sweep the porch or driveway.",
    "Help wash the car outside.",
    "Help out in the garden.",
    "Water the plants outside.",
    "Walk the dog.",
    "Shoot some free throws.",
    "Practice dribbling a soccer ball.",
    "Jump on a trampoline.",
    "Practice a handstand or cartwheel.",
    "Do a nature scavenger hunt in your yard.",
    "Look for shapes in the clouds.",
    "Watch the sunset from outside.",
    "Collect interesting leaves or rocks on a walk.",
    "Try a new outdoor game you've never played.",
    "Do a lap or two around the yard.",
    "Practice your bike-riding skills.",
    "Go for a scooter ride.",
    "Try jumping rope backwards.",
    "Do a stretching routine outside.",
    "Walk somewhere close instead of getting a ride.",
    "Practice kicking a ball into a goal.",
    "Try skipping instead of walking for a bit.",
    "Do wall push-ups outside.",
    "Try balancing on one foot for as long as you can.",
    "Practice your best cartwheel.",
    "Go outside and count how many different birds you see.",
    "Try racing yourself around the yard and beat your time.",
    "Practice catching a ball with one hand.",
    "Go outside and just run around for fun.",
    "Practice your jump shot.",
    "Try hula hooping outside.",
    "Practice riding your bike with no hands, carefully and somewhere safe.",
    "Go for a walk and notice five different trees.",
    "Try a cartwheel contest with yourself.",
    "Practice long jump in the yard.",
    "See how many jumping jacks you can do in a minute.",
    "Practice balancing while walking heel-to-toe.",
    "Try skipping rocks across water.",
    "Go outside and do ten minutes of any sport you like.",
    "Practice a new trick on your bike or scooter.",
    "Walk to a nearby spot instead of riding.",
    "Spend recess time being active outside.",
    "Try climbing something safe, like a low tree or rock.",
    "Go outside and try to spot animals or insects.",
    "Practice your throwing arm.",
    "Do a set of squats or lunges outside.",
    "Try walking backwards safely in the yard.",
    "Practice dribbling a basketball around obstacles.",
    "Go for a walk and time yourself.",
    "Try a scavenger hunt for different colors outside.",
    "Do some outdoor stretching before bed.",
    "Practice your serve if you play a racket sport.",
    "Go outside and try three new stretches.",
    "Walk laps around your yard while listening to music.",
    "Try an outdoor workout video.",
    "Practice your goalie skills if you play soccer.",
    "Go outside and just move for 20 minutes.",
    "Play tag with a friend.",
    "Play catch with someone.",
    "Go for a bike ride with a friend.",
    "Shoot hoops with a friend.",
    "Play frisbee with someone.",
    "Have a jump rope contest.",
    "Play hide and seek outside.",
    "Have a race around the yard with someone.",
    "Play badminton with a friend.",
    "Build an obstacle course with a friend.",
    "Play soccer with friends.",
    "Go for a walk with a family member.",
    "Go for a hike with a friend.",
    "Play catch with a parent.",
    "Have a water balloon toss with someone.",
    "Do a scavenger hunt with a friend.",
    "Play tag with your siblings.",
    "Go for a bike ride with family.",
    "Play basketball with a friend.",
    "Have a three-legged race with someone.",
    "Play hopscotch with a friend.",
    "Fly a kite with someone.",
    "Go stargazing with your family.",
    "Play catch with a sibling.",
    "Have a dance party outside with friends.",
    "Play a pickup game of soccer.",
    "Race a friend to the end of the block.",
    "Play catch with a neighbor.",
    "Go for a walk with the family dog.",
    "Build a fort outside with a friend.",
    "Have a jumping contest to see who can jump farthest.",
    "Play a game of tag at the park.",
    "Go biking with a sibling.",
    "Teach a friend a sport move you know.",
    "Have a hula hoop contest.",
    "Play a backyard game with the whole family.",
    "Kick a ball around with a parent.",
    "Go for a walk and talk with a grandparent.",
    "Have a relay race in the yard.",
    "Play catch until you drop the ball five times.",
    "Go exploring outside with a friend.",
    "Play a game of horse at the basketball hoop.",
    "Have a handstand contest with a friend.",
    "Go for a walk with a neighbor's kid.",
    "Play tug of war with friends.",
    "Have a bike race around the block.",
    "Play a game of capture the flag.",
    "Go on a bug hunt with a sibling.",
    "Have a cartwheel contest with friends.",
    "Play catch with a football.",
    "Build a sandcastle with a friend."
)

val PARENT_DAILY_TIPS = listOf(
    "Today, go for a walk with your kid.",
    "Today, go for a bike ride together.",
    "Today, shoot some hoops with your kid.",
    "Today, kick a ball around together.",
    "Today, play catch with your kid.",
    "Today, go for a hike together.",
    "Today, take a walk around the neighborhood together.",
    "Today, go for a jog together.",
    "Today, play frisbee together.",
    "Today, fly a kite together.",
    "Today, do a stretching routine together outside.",
    "Today, go for a swim together.",
    "Today, play a backyard game together.",
    "Today, go to a park together.",
    "Today, go for a scooter or bike ride together.",
    "Today, play tag with your kid.",
    "Today, have a race around the yard.",
    "Today, do yoga outside together.",
    "Today, go for a walk and talk about their day.",
    "Today, play soccer together.",
    "Today, go stargazing together.",
    "Today, take a walk after dinner together.",
    "Today, go for a walk with the family dog.",
    "Today, build an obstacle course together in the yard.",
    "Today, have a three-legged race together.",
    "Today, play badminton together.",
    "Today, go birdwatching together.",
    "Today, take a bike ride around the block together.",
    "Today, play basketball together.",
    "Today, go for a hike on a nearby trail together.",
    "Today, do a scavenger hunt outside together.",
    "Today, play catch until you both lose count.",
    "Today, go outside and toss a frisbee back and forth.",
    "Today, take a walk somewhere new together.",
    "Today, watch the sunset outside together.",
    "Today, go for a jog or walk before dinner together.",
    "Today, have a dance party outside together.",
    "Today, play a pickup game of soccer together.",
    "Today, go apple-picking, berry-picking, or another outdoor outing together.",
    "Today, spend twenty minutes just playing outside together, no agenda.",
    "Today, have a water balloon fight together.",
    "Today, build a fort outside together.",
    "Today, go on a bike ride to somewhere new.",
    "Today, play horse at the basketball hoop together.",
    "Today, go for a walk and point out five things you both like about the neighborhood.",
    "Today, race each other around the block.",
    "Today, play catch with a football together.",
    "Today, try a new outdoor game together.",
    "Today, take a family walk after a meal.",
    "Today, go outside and just move together for 20 minutes.",
    "Today, help your kid practice a sport skill outside.",
    "Today, go for a walk and collect leaves together.",
    "Today, have a hula hoop contest together.",
    "Today, play kickball or wiffle ball together.",
    "Today, go for a walk somewhere with a nice view.",
    "Today, take a bike ride to get ice cream or a treat.",
    "Today, spend time gardening together outside.",
    "Today, rake leaves together and jump in the pile.",
    "Today, go for a walk or run for yourself.",
    "Today, spend some time outside stretching.",
    "Today, take a walk during your lunch break.",
    "Today, go for a bike ride on your own.",
    "Today, spend 15 minutes outside without your phone.",
    "Today, take a walk to clear your head.",
    "Today, do a short outdoor workout for yourself.",
    "Today, spend time in the garden.",
    "Today, go for a walk around the block before starting your day.",
    "Today, step outside for some fresh air between tasks.",
    "Today, take a walk after dinner to unwind.",
    "Today, do some stretching outside before bed.",
    "Today, go for a jog to start your morning.",
    "Today, spend a few minutes outside with your coffee.",
    "Today, take the stairs or a walk instead of driving somewhere close.",
    "Today, go for a walk and call a friend while you do it.",
    "Today, ask your kid an open-ended question about their day, with no screen nearby.",
    "Today, have a phone-free conversation with your kid.",
    "Today, call your own parent or a relative.",
    "Today, write your kid a short note and leave it somewhere they'll find it.",
    "Today, ask your kid to teach you something they're into.",
    "Today, cook or bake something together with your kid.",
    "Today, play a board game with your kid.",
    "Today, have breakfast together and really talk.",
    "Today, put your phone away during dinner tonight.",
    "Today, ask your kid what they'd like to do together this weekend.",
    "Today, tell your kid something specific you're proud of them for.",
    "Today, check in with a friend you haven't talked to in a while.",
    "Today, ask your kid to show you their favorite hobby up close.",
    "Today, write down three things you appreciate about your kid and tell them.",
    "Today, ask your kid three questions about their friends.",
    "Today, help your kid with something they're working on.",
    "Today, thank your kid for something they did recently.",
    "Today, ask a grandparent to share a story with your kid.",
    "Today, plan a family game night.",
    "Today, have a meal together with no devices at the table.",
    "Today, ask your kid what their favorite part of today was.",
    "Today, reach out to a neighbor and see how they're doing.",
    "Today, ask your kid to teach you a game or trick they're good at.",
    "Today, write a letter to your kid about something you love about them.",
    "Today, spend ten minutes really listening to your kid, no interrupting.",
    "Today, help your kid write a thank-you note to someone.",
    "Today, ask your kid what they'd like more of from you this week.",
    "Today, plan a small kindness project together, like baking for a neighbor.",
    "Today, ask your kid to help you plan a surprise for someone else.",
    "Today, call a friend just to catch up.",
    "Today, ask your kid about their favorite memory this year.",
    "Today, sit down with your kid and ask about their friendships.",
    "Today, compliment your kid on something you've noticed lately.",
    "Today, ask your kid to help you cook, even if it's messier that way.",
    "Today, reconnect with an old friend you've lost touch with.",
    "Today, ask your kid what rule or routine they'd change if they could.",
    "Today, tell your kid a story from when you were their age.",
    "Today, help your kid plan a get-together with a friend.",
    "Today, ask your kid to teach a sibling something they know.",
    "Today, give your kid your full attention for ten minutes, phone away.",
    "Today, ask your kid what they're looking forward to this week.",
    "Today, invite a family member over for a meal.",
    "Today, thank your kid's teacher or coach for something they've done.",
    "Today, ask your kid what made them laugh.",
    "Today, write down a family goal for the week and talk about it together.",
    "Today, ask your kid to help plan next week's dinner menu.",
    "Today, spend time with your kid doing something they chose, not you.",
    "Today, ask your kid about a book, show, or game they love and really listen.",
    "Today, check in with your own sibling or close friend.",
    "Today, plan a visit with a grandparent or relative.",
    "Today, ask your kid what they'd like to learn together.",
    "Today, tell your kid about a mistake you made and what you learned.",
    "Today, help your kid write a letter to a relative.",
    "Today, ask your kid to pick the family activity tonight.",
    "Today, share a meal with your kid with no TV or phones on.",
    "Today, ask your kid what kind of day they're hoping for tomorrow.",
    "Today, spend a few minutes asking your kid about their friends' lives.",
    "Today, tell your kid a joke and see if you can make them laugh.",
    "Today, ask your kid to show you something they made or drew recently.",
    "Today, plan one-on-one time with each of your kids this week.",
    "Today, reach out to someone you've been meaning to thank.",
    "Today, ask your kid what their day would look like if they planned it.",
    "Today, tell your kid about your own favorite hobby growing up.",
    "Today, help your kid think through a problem they're facing, just by listening.",
    "Today, ask your kid to help you write a card for someone.",
    "Today, sit with your kid while they do something they enjoy, just to be near them.",
    "Today, ask your kid what they wish you understood better about them.",
    "Today, thank your own partner or co-parent for something specific.",
    "Today, ask your kid about the best part of their friend group.",
    "Today, call a relative your kid doesn't talk to often and put them on the line too.",
    "Today, ask your kid what they'd want to teach you if they were the parent for a day.",
    "Today, write your kid a list of things you're grateful they're in your life.",
    "Go for a walk with your kid.",
    "Go for a bike ride together.",
    "Shoot some hoops with your kid.",
    "Kick a ball around together.",
    "Play catch with your kid.",
    "Go for a hike together.",
    "Take a walk around the neighborhood together.",
    "Go for a jog together.",
    "Play frisbee together.",
    "Fly a kite together.",
    "Do a stretching routine together outside.",
    "Go for a swim together.",
    "Play a backyard game together.",
    "Go to a park together.",
    "Go for a scooter or bike ride together.",
    "Play tag with your kid.",
    "Have a race around the yard.",
    "Do yoga outside together.",
    "Go for a walk and talk about their day.",
    "Play soccer together.",
    "Go stargazing together.",
    "Take a walk after dinner together.",
    "Go for a walk with the family dog.",
    "Build an obstacle course together in the yard.",
    "Have a three-legged race together.",
    "Play badminton together.",
    "Go birdwatching together.",
    "Take a bike ride around the block together.",
    "Play basketball together.",
    "Go for a hike on a nearby trail together.",
    "Do a scavenger hunt outside together.",
    "Play catch until you both lose count.",
    "Go outside and toss a frisbee back and forth.",
    "Take a walk somewhere new together.",
    "Watch the sunset outside together.",
    "Go for a jog or walk before dinner together.",
    "Have a dance party outside together.",
    "Play a pickup game of soccer together.",
    "Go apple-picking, berry-picking, or another outdoor outing together.",
    "Spend twenty minutes just playing outside together, no agenda.",
    "Have a water balloon fight together.",
    "Build a fort outside together.",
    "Go on a bike ride to somewhere new.",
    "Play horse at the basketball hoop together.",
    "Go for a walk and point out five things you both like about the neighborhood.",
    "Race each other around the block.",
    "Play catch with a football together.",
    "Try a new outdoor game together.",
    "Take a family walk after a meal.",
    "Go outside and just move together for 20 minutes.",
    "Help your kid practice a sport skill outside.",
    "Go for a walk and collect leaves together.",
    "Have a hula hoop contest together.",
    "Play kickball or wiffle ball together.",
    "Go for a walk somewhere with a nice view.",
    "Take a bike ride to get ice cream or a treat.",
    "Spend time gardening together outside.",
    "Rake leaves together and jump in the pile.",
    "Go for a walk or run for yourself.",
    "Spend some time outside stretching.",
    "Take a walk during your lunch break.",
    "Go for a bike ride on your own.",
    "Spend 15 minutes outside without your phone.",
    "Take a walk to clear your head.",
    "Do a short outdoor workout for yourself.",
    "Spend time in the garden.",
    "Go for a walk around the block before starting your day.",
    "Step outside for some fresh air between tasks.",
    "Take a walk after dinner to unwind.",
    "Do some stretching outside before bed.",
    "Go for a jog to start your morning.",
    "Spend a few minutes outside with your coffee.",
    "Take the stairs or a walk instead of driving somewhere close.",
    "Go for a walk and call a friend while you do it.",
    "Ask your kid an open-ended question about their day, with no screen nearby.",
    "Have a phone-free conversation with your kid.",
    "Call your own parent or a relative.",
    "Write your kid a short note and leave it somewhere they'll find it.",
    "Ask your kid to teach you something they're into.",
    "Cook or bake something together with your kid.",
    "Play a board game with your kid.",
    "Have breakfast together and really talk.",
    "Put your phone away during dinner tonight.",
    "Ask your kid what they'd like to do together this weekend.",
    "Tell your kid something specific you're proud of them for.",
    "Check in with a friend you haven't talked to in a while.",
    "Ask your kid to show you their favorite hobby up close.",
    "Write down three things you appreciate about your kid and tell them.",
    "Ask your kid three questions about their friends.",
    "Help your kid with something they're working on.",
    "Thank your kid for something they did recently.",
    "Ask a grandparent to share a story with your kid.",
    "Plan a family game night.",
    "Have a meal together with no devices at the table.",
    "Ask your kid what their favorite part of today was.",
    "Reach out to a neighbor and see how they're doing.",
    "Ask your kid to teach you a game or trick they're good at.",
    "Write a letter to your kid about something you love about them.",
    "Spend ten minutes really listening to your kid, no interrupting.",
    "Help your kid write a thank-you note to someone.",
    "Ask your kid what they'd like more of from you this week.",
    "Plan a small kindness project together, like baking for a neighbor.",
    "Ask your kid to help you plan a surprise for someone else.",
    "Call a friend just to catch up.",
    "Ask your kid about their favorite memory this year.",
    "Sit down with your kid and ask about their friendships.",
    "Compliment your kid on something you've noticed lately.",
    "Ask your kid to help you cook, even if it's messier that way.",
    "Reconnect with an old friend you've lost touch with.",
    "Ask your kid what rule or routine they'd change if they could.",
    "Tell your kid a story from when you were their age.",
    "Help your kid plan a get-together with a friend.",
    "Ask your kid to teach a sibling something they know.",
    "Give your kid your full attention for ten minutes, phone away.",
    "Ask your kid what they're looking forward to this week.",
    "Invite a family member over for a meal.",
    "Thank your kid's teacher or coach for something they've done.",
    "Ask your kid what made them laugh.",
    "Write down a family goal for the week and talk about it together.",
    "Ask your kid to help plan next week's dinner menu.",
    "Spend time with your kid doing something they chose, not you.",
    "Ask your kid about a book, show, or game they love and really listen.",
    "Check in with your own sibling or close friend.",
    "Plan a visit with a grandparent or relative.",
    "Ask your kid what they'd like to learn together.",
    "Tell your kid about a mistake you made and what you learned.",
    "Help your kid write a letter to a relative.",
    "Ask your kid to pick the family activity tonight.",
    "Share a meal with your kid with no TV or phones on.",
    "Ask your kid what kind of day they're hoping for tomorrow.",
    "Spend a few minutes asking your kid about their friends' lives.",
    "Tell your kid a joke and see if you can make them laugh.",
    "Ask your kid to show you something they made or drew recently.",
    "Plan one-on-one time with each of your kids this week.",
    "Reach out to someone you've been meaning to thank.",
    "Ask your kid what their day would look like if they planned it.",
    "Tell your kid about your own favorite hobby growing up.",
    "Help your kid think through a problem they're facing, just by listening.",
    "Ask your kid to help you write a card for someone.",
    "Sit with your kid while they do something they enjoy, just to be near them.",
    "Ask your kid what they wish you understood better about them.",
    "Thank your own partner or co-parent for something specific.",
    "Ask your kid about the best part of their friend group.",
    "Call a relative your kid doesn't talk to often and put them on the line too.",
    "Ask your kid what they'd want to teach you if they were the parent for a day.",
    "Write your kid a list of things you're grateful they're in your life.",
    "See if you can go for a walk with your kid today.",
    "See if you can go for a bike ride together today.",
    "See if you can shoot some hoops with your kid today.",
    "See if you can kick a ball around together today.",
    "See if you can play catch with your kid today.",
    "See if you can go for a hike together today.",
    "See if you can take a walk around the neighborhood together today.",
    "See if you can go for a jog together today.",
    "See if you can play frisbee together today.",
    "See if you can fly a kite together today.",
    "See if you can do a stretching routine together outside today.",
    "See if you can go for a swim together today.",
    "See if you can play a backyard game together today.",
    "See if you can go to a park together today.",
    "See if you can go for a scooter or bike ride together today.",
    "See if you can play tag with your kid today.",
    "See if you can have a race around the yard today.",
    "See if you can do yoga outside together today.",
    "See if you can go for a walk and talk about their day today.",
    "See if you can play soccer together today.",
    "See if you can go stargazing together today.",
    "See if you can take a walk after dinner together today.",
    "See if you can go for a walk with the family dog today.",
    "See if you can build an obstacle course together in the yard today.",
    "See if you can have a three-legged race together today.",
    "See if you can play badminton together today.",
    "See if you can go birdwatching together today.",
    "See if you can take a bike ride around the block together today.",
    "See if you can play basketball together today.",
    "See if you can go for a hike on a nearby trail together today.",
    "See if you can do a scavenger hunt outside together today.",
    "See if you can play catch until you both lose count today.",
    "See if you can go outside and toss a frisbee back and forth today.",
    "See if you can take a walk somewhere new together today.",
    "See if you can watch the sunset outside together today.",
    "See if you can go for a jog or walk before dinner together today.",
    "See if you can have a dance party outside together today.",
    "See if you can play a pickup game of soccer together today.",
    "See if you can go apple-picking, berry-picking, or another outdoor outing together today.",
    "See if you can spend twenty minutes just playing outside together, no agenda today.",
    "See if you can have a water balloon fight together today.",
    "See if you can build a fort outside together today.",
    "See if you can go on a bike ride to somewhere new today.",
    "See if you can play horse at the basketball hoop together today.",
    "See if you can go for a walk and point out five things you both like about the neighborhood today.",
    "See if you can race each other around the block today.",
    "See if you can play catch with a football together today.",
    "See if you can try a new outdoor game together today.",
    "See if you can take a family walk after a meal today.",
    "See if you can go outside and just move together for 20 minutes today.",
    "See if you can help your kid practice a sport skill outside today.",
    "See if you can go for a walk and collect leaves together today.",
    "See if you can have a hula hoop contest together today.",
    "See if you can play kickball or wiffle ball together today.",
    "See if you can go for a walk somewhere with a nice view today.",
    "See if you can take a bike ride to get ice cream or a treat today.",
    "See if you can spend time gardening together outside today.",
    "See if you can rake leaves together and jump in the pile today.",
    "See if you can go for a walk or run for yourself today.",
    "See if you can spend some time outside stretching today.",
    "See if you can take a walk during your lunch break today.",
    "See if you can go for a bike ride on your own today.",
    "See if you can spend 15 minutes outside without your phone today.",
    "See if you can take a walk to clear your head today.",
    "See if you can do a short outdoor workout for yourself today.",
    "See if you can spend time in the garden today.",
    "See if you can go for a walk around the block before starting your day today.",
    "See if you can step outside for some fresh air between tasks today.",
    "See if you can take a walk after dinner to unwind today.",
    "See if you can do some stretching outside before bed today.",
    "See if you can go for a jog to start your morning today.",
    "See if you can spend a few minutes outside with your coffee today.",
    "See if you can take the stairs or a walk instead of driving somewhere close today."
)
/**
 * A stable index for "which day is it" - the same value for one calendar day (UTC),
 * advancing by one every day, so the tip stays put for the day and changes tomorrow.
 */
fun currentDayIndex(nowMillis: Long = System.currentTimeMillis()): Int = (nowMillis / MILLIS_PER_DAY).toInt()

fun currentDayKidTip(): String = KID_DAILY_TIPS[currentDayIndex().mod(KID_DAILY_TIPS.size)]

fun currentDayParentTip(): String = PARENT_DAILY_TIPS[currentDayIndex().mod(PARENT_DAILY_TIPS.size)]

private const val MILLIS_PER_DAY = 86_400_000L
